name: "ipython notebook research website"
repo: "http://github.com/pcarbo/ipynb-demo"
footer: "&copy 2017 Peter Carbonetto"
include_dir: ["analysis"]
homepage: "analysis/Overview.ipynb"
source_label: "source"
theme: "readable"
font: NULL
#release_message: "Build website via jnbinder"
