name: "m&m ash"
repo: "http://github.com/gaow/mvarbvs"
footer: "&copy 2016-2017 Stephenslab, University of Chicago"
exclude_dir: ["src", "reference", "data"]
disqus: NULL
commit_message: "Update website via jnbinder"
post_push_actions: "echo 'for additional commands after push'"
